### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by yazgoo** [jp/ambari#10]
Hi,

Thanks for this cookbook, but on Ubuntu 15.04,
I'm having this error on the agent:

````
ERROR 2015-10-12 14:39:49,408 NetUtil.py:78 - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
ERROR 2015-10-12 14:39:49,408 NetUtil.py:79 - SSLError: Failed to connect. Please check openssl library versions.
Refer to: https://bugzilla.redhat.com/show_bug.cgi?id=1022468 for more details.
````

When I curl the server port 8440, I'm getting:

````
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
````

Any suggestion ?

**Comment by jp** [comment]
Hello,

Using the "-k" option as suggested in the curl output would help you to debug as curl will accept the certificate.

Aside of that, Ubuntu 15.04 is not officially supported by Ambari as per their documentation: http://docs.hortonworks.com/HDPDocuments/Ambari-2.1.2.0/bk_Installing_HDP_AMB/content/_operating_systems_requirements.html

I'd suggest you to switch to a supported OS.

Cheers,
J

**Comment by yazgoo** [comment]
Yeah, that's what I did.

Thanks jp

**Comment by finalcreator** [comment]
you can try to comment out the "NetUtil.py" file at 70, 
      #FIXME force non-verification of SSL certs - Tom 2/7/2018
      #if sys.version_info >= (2,7,9) and not ssl_verify_cert:
      import ssl
      ca_connection = httplib.HTTPSConnection(parsedurl[1], context=ssl._create_unverified_context())
      # else:
      #     ca_connection = httplib.HTTPSConnection(parsedurl[1])
