### ISSUE TITLE
setup_package_manager.rb misses case for rhel7

### ISSUE THREAD

**Issue by Paul424** [jp/ambari#15]
For ambari v2.1 the attribute rhel_7_repo is set already but the case is missing so the repo is not selected making the recipe fail.

Fix:

case node['platform']
when 'redhat', 'centos', 'amazon', 'scientific'
  case node['platform_version'].to_i
  when 5
    yum_repo = node['ambari']['rhel_5_repo']
  when 6
    yum_repo = node['ambari']['rhel_6_repo']
  when 7
    yum_repo = node['ambari']['rhel_7_repo']
  end
  remote_file '/etc/yum.repos.d/ambari.repo' do
    source yum_repo
    not_if { ::File.exist?('/etc/yum.repos.d/ambari.repo') }
  end

**Comment by Joseph-R** [comment]
Hey Paul!  Good catch.  Thanks for the feedback.

Closed by 0af82b3.
