### ISSUE TITLE
Conflicting version of snappy 1.1.0; ambari requires 1.0.5 for rhel7

### ISSUE THREAD

**Issue by Paul424** [jp/ambari#16]
Julien; while trying ambari to deploy applications throughout the cluster we encountered an issue with the version of snappy; it's a known problem for rhel7/hdp, see http://docs.hortonworks.com/HDPDocuments/Ambari-2.1.1.0/bk_releasenotes_ambari_2.1.0.0/content/ambari_relnotes-2.1.0.0-known-issues.html

resource_management.core.exceptions.
Fail: Execution of '/usr/bin/yum -d 0 -e 0 -y install snappy-devel' returned 1.
Error: Package: snappy-devel-1.0.5-1.el6.x86_64 (HDP-UTILS-1.1.0.20)
           Requires: snappy(x86-64) = 1.0.5-1.el6
           Installed: snappy-1.1.0-3.el7.x86_64 (@anaconda/7.1)
               snappy(x86-64) = 1.1.0-3.el7
           Available: snappy-1.0.5-1.el6.x86_64 (HDP-UTILS-1.1.0.20)
               snappy(x86-64) = 1.0.5-1.el6        

A fix can be to add following to the agent recipe:

yum_package 'remove snappy 1.1.0-3.el7' do
  package_name 'snappy'
  version '1.1.0-3.el7'
  action :remove
end

I realize that this may not be the best solution as the version is hardcoded and did not test other platforms or ambari versions.

Paul

**Comment by jp** [comment]
Hello,
I'm not sure about this one. I think this should be fixed soon in the dependencies of the packages.
My take is that the cookbook should not try to such dependencies issues.
I'm closing this for now, please tell me if this is still an issue.
Thanks
