### ISSUE TITLE
External Database Config

### ISSUE THREAD

**Issue by habelson** [jp/ambari#22]
Is there a way to pass in external database configuration for ambari-server to use instead of defaulting to the embedded postgres? If not, this would be in incredibly useful feature

**Comment by Joseph-R** [comment]
I agree.  We should probably refactor that part and allow selection of an external DB.

**Comment by habelson** [comment]
I saw that was touched on with PR #20 .. did that ever go anywhere?

**Comment by jp** [comment]
The code in #20 was merged, would you be able to tell be if this is is working for you?
