### ISSUE TITLE
Add support for Ambari 2.0, other versions.

### ISSUE THREAD

**Issue by Joseph-R** [jp/ambari#4]
Hey guys!

Ambari 2.0 has been out for awhile now.  There are some [pretty significant changes](http://www.slideshare.net/hortonworks/apache-ambari-whats-new-in-200), so I think it's probably a good idea to support multiple versions.

I have a forked version supporting 2.0 I've been running for about a week now.  I'll put together a pull request if there is interest in that.

Regards,
Joe Reid

**Comment by jp** [comment]
Closed by https://github.com/jp/ambari/pull/5.
Cheers.
